### ISSUE TITLE
Add Input as Shell imitation

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#1]
## Value proposition

**As a** game-driven wannabe Coder
**I want to** use an Input-element that imitates the zshell
**so that** i can learn the commands by playing a little game.

## Description

<img src="https://user-images.githubusercontent.com/104508413/175257928-e6a347cf-686c-4528-9302-5308912cfe90.svg" width=320px>

## Acceptance criteria

- [ ] An Input that accepts zshell commands
- [ ] An overview of used commands
- [ ] the overview is scrollable 
- [ ] the overview is always at the bottom on last used-command-log, when i submit a new command
- [ ] Additional Information and Feedback for my commands
- [ ] The Input should look and feel like a terminal
- [ ] some Text, that explains for me the basic use

## Complexity

Small/Medium

## Tasks

- [ ] Create branch
- [ ] create input with buttons to submit next to it.
- [ ] display switch from "▯" to "▮" when focus on input and switch back if not.
- [ ] useable commands, that work like in the shell: 
- - [ ] `pwd` - current location 
- - [ ] `ls` for further information about current position or `ls loc/path/name` about other position in the maze  
- - [ ] `cd nextPath` to switch to a new room or `cd ..` to go back to previous room.
- [ ] section with used commands as list with list items
- [ ] section is y-scrollable, but limited on x-axis.
- [ ] list items contains a list for further information (info about used command / effect of command)
- [ ] the Input is connected to an array, so the user can move from index to index, as from room to room.
- [ ] the Room<->Input check is string-based (so i don't have a lot of abstract numbers in the end)
- [ ] user should get warned or informed if he/she/div uses invalid commands.
- [ ] little text with description and basic commands to understand how to use it at this point
- [ ] spec.tests for the input
- [ ] storybook for the Form-Input with buttons and styling to imitate the terminal.
<br>
