### ISSUE TITLE
spell ls-a reveals hidden content

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#12]
## Value proposition

**As a** user,
**I want to** have hidden content
**so that** i get rewarded when i find some of it

## Description

<img src="https://user-images.githubusercontent.com/104508413/179539125-94f7d484-4cd8-4e86-b4e6-d7dac55048ad.png" width=1000px>

## Acceptance criteria

- [ ] some Rooms have hidden content that the user can make visible with "ls-a" and enter

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] add new `else if{ }` inside of "lsSpell"-function
- [ ] add hidden paths to rooms, that are marked with "."-sign
- [ ] hidden paths are only shown when "ls-a" is submited
