### ISSUE TITLE
Add titlescreen before game

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#13]
## Value proposition

**As a** user,
**I want to** have a titlescreen
**so that** i have a moment to get in the right mood

## Description

<img src="https://user-images.githubusercontent.com/104508413/179541146-f4397c91-481a-463c-a810-a3684393b76b.png" width=800px>

## Acceptance criteria

- [ ] a titlescreen with a button is first page after opening or reloading the app.
- [ ] when user presses button user is directed to game-page.
- [ ] introduction text is now on titlescreen-page.
- [ ] a cancel button directs from game-page back to titlescreen-page.

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] implement routing
- [ ] create button to switch from titlescreen to game
- [ ] create button to cancel current game and return to titlescreen
- [ ] message is shown to check if cancel was correct
- [ ] if cancel was incorrect the focus is set on the input

**Comment by JessicaLoers** [comment]
Looks good to me 👍
