### ISSUE TITLE
Add visual feedback on canvas

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#2]
## Value proposition

**As a** game-driven wannabe Coder,
**I want to** get visual feedback for my actions,
**so that** i can imagine my doings more well and entertaining

## Description

<img src="https://user-images.githubusercontent.com/104508413/175273548-339ab19b-a64a-4010-ad76-f5a1ee9d87ee.svg" width=320px>

## Acceptance criteria

- [ ] a section that shows images, which change through user actions
- [ ] a few animations that undermine specific actions (npc-characters fading in&out or moving in&out)
- [ ] specific rooms have specific images, so that the maze feels like a scene
- [ ] all the drawings are quite nice and unique crafted

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] test and research how to use html<canvas> for my project (hopefully <canvas> will give me the possibilities i search for, otherwise this will be striked through ~~like this~~)
- [ ] find a good format/size for the imagepart
- [ ] add images and sprites to project and 
- [ ] connect images and sprites to the objects in the position-maze-array as value
- [ ] add an animation for command `ls` that turns a dark room into a light room
- [ ] create first npc's and items as values of specific objects in the array
- [ ] npc's and items are displayed dynamically through (hopefully) html<canvas> (otherwise static)
- [ ] add new command: `cat npc.item` to get specific information about/from the npc.item
