### ISSUE TITLE
Give out Information

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#4]
## Value proposition

**As a** user,
**I want to** learn the zshell commands
**so that** I can get information about what the command does

## Description

<img src='https://user-images.githubusercontent.com/104508413/175880072-8bf94367-ca65-47ba-b485-dec7edd55ab4.svg' width=640px>

## Acceptance criteria

- [x] the user can submit his writing when pressing enter or using the button
- [x] user gets information for `pwd`,`ls` and `cd` if spelled correctly in Input and submitted it
- [x] submitted information is added to the bottom of a list
- [x] error message will appear in list if the Input does not match a valid command
- [x] the list with printed information is limited and scrollable on y-axis, but not on x-axis

## Complexity

Small

## Tasks

- [x] Create branch
- [x] create Form
- [x] create a function to analyze the string from the Form
- [x] create a list to save the string from the Form
- [x] string from Form gets trimmed
- [x] error message will be printed if string from Form does not match if-statements in analyzing function
- [x] create Tests
- [x] create Stories

**Comment by mbosselmann** [comment]
Hi Georg,
good job! 😎 I have two remarks about your user story:

**Value proposition:**
- "so that i can type them in my app and get information about" I think this part is not finished yet? Maybe: "so that I can get information about what the command does"?

**Acceptance criteria:**
- I have a question about this criterion: "the user can submit his writing when pressing enter or using the button": It is not clear to me if the information about the shell commands is only displayed when the user submits the command. Or is it automatically displayed what the command means? And I was wondering if the user is informed if he has mistyped? Maybe you can describe this further in your acceptance criteria and show in a wireframe what happens when the user makes a mistake?

I hope these remarks will help you. Feel free to ask me if you have questions. :)

**Comment by GeorgJuranek** [comment]
Hello, thanks a lot for your feedback!
I tried to correct my value proposition and acceptance criteria, i hope its now more understandable what i am planning to do with this. Please let me know if this solved your remarks about it.
Greetings!

**Comment by mbosselmann** [comment]
Hi Georg,
looks good to me! Only one nit-picking remark: The image is really small and the text ist hard to read. Maybe you can add a larger image? 😅 Everything else is alright. 👍 

Happy hacking! :)

**Comment by GeorgJuranek** [comment]
Oh you're right (of course), I forgot to update the width. Thanks a lot, i will put this in my sprint now!

**Comment by GeorgJuranek** [comment]
can you give me the ☑️ in the channel, so i have no guilty conscience 😇 thanks
