### ISSUE TITLE
Scrolling set to bottom position

### ISSUE THREAD

**Issue by GeorgJuranek** [GeorgJuranek/capstone-project#5]
## Value proposition

**As a** user,
**I want to** have a more accurate visualization of a shell
**so that** i can feel like using one

## Description

<img 
src="https://user-images.githubusercontent.com/104508413/175477937-66c177b6-c642-4e53-8a02-091101d30c59.svg"
width=320px>

## Acceptance criteria

- [ ] when user confirms action given message is at bottom of section
- [ ] when scrolling up in section, a new submit sets scrolling position to bottom

## Complexity

Small

## Tasks

- [ ] Create branch
- [ ] printed out information is at bottom of section
- [ ] new submit sets scrolling position to section bottom on the new submit
- [ ] write test
- [ ] write story
